name: Terraform Infrastructure

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Selecciona la acción a ejecutar'
        required: true
        type: choice
        options:
          - apply
          - destroy
        default: apply

jobs:
  infrastructure:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infrastructure

    steps:
      - uses: actions/checkout@v4

      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        run: terraform init
        env:
          ARM_CLIENT_ID: ${{ fromJson(secrets.AZURE_CREDENTIALS).clientId }}
          ARM_CLIENT_SECRET: ${{ fromJson(secrets.AZURE_CREDENTIALS).clientSecret }}
          ARM_SUBSCRIPTION_ID: ${{ fromJson(secrets.AZURE_CREDENTIALS).subscriptionId }}
          ARM_TENANT_ID: ${{ fromJson(secrets.AZURE_CREDENTIALS).tenantId }}

      - name: List Container App Environments
        run: az containerapp env list -o table
        env:
          ARM_CLIENT_ID: ${{ fromJson(secrets.AZURE_CREDENTIALS).clientId }}
          ARM_CLIENT_SECRET: ${{ fromJson(secrets.AZURE_CREDENTIALS).clientSecret }}
          ARM_SUBSCRIPTION_ID: ${{ fromJson(secrets.AZURE_CREDENTIALS).subscriptionId }}
          ARM_TENANT_ID: ${{ fromJson(secrets.AZURE_CREDENTIALS).tenantId }}

      - name: Terraform Action
        run: |
          if [ "${{ github.event.inputs.action }}" = "destroy" ]; then
            echo "🚨 Destruyendo Infraestructura Principal..."
            terraform plan -destroy
            terraform destroy -auto-approve
          else
            echo "🛠 Aplicando Infraestructura Principal..."
            terraform plan -out=tfplan \
              -var="backend_image=${{ secrets.BACKEND_IMAGE }}" \
              -var="frontend_image=${{ secrets.FRONTEND_IMAGE }}"
            terraform apply -auto-approve tfplan
          fi
        env:
          ARM_CLIENT_ID: ${{ fromJson(secrets.AZURE_CREDENTIALS).clientId }}
          ARM_CLIENT_SECRET: ${{ fromJson(secrets.AZURE_CREDENTIALS).clientSecret }}
          ARM_SUBSCRIPTION_ID: ${{ fromJson(secrets.AZURE_CREDENTIALS).subscriptionId }}
          ARM_TENANT_ID: ${{ fromJson(secrets.AZURE_CREDENTIALS).tenantId }}